---
# lint: |
#   set -e
#   yamllint .
#   ansible-lint -vv --exclude=.tox
scenario:
  name: star
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
provisioner:
  name: ansible
  log: True
  inventory:
    host_vars:
      tinc-centos-7:
        tinc_vpn_ip: 10.10.0.11
      tinc-centos-8:
        tinc_vpn_ip: 10.10.0.12
      tinc-ubuntu-18:
        tinc_vpn_ip: 10.10.0.14
      tinc-ubuntu-20:
        tinc_vpn_ip: 10.10.0.15

platforms:
  - name: tinc-centos-7
    image: centos-7
    privileged: true
    command: /sbin/init 
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro    
    etc_hosts:
      tinc-centos-7:  10.10.0.11
      tinc-centos-8:  10.10.0.12
      tinc-ubuntu-18: 10.10.0.14
      tinc-ubuntu-20: 10.10.0.15
    groups:
      - tinc_nodes
      - tinc_spine_nodes
      - tinc_leaf_nodes

  - name: tinc-centos-8
    image: centos-8
    privileged: true
    command: /sbin/init
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro    
    etc_hosts:
      tinc-centos-7:  10.10.0.11
      tinc-centos-8:  10.10.0.12
      tinc-ubuntu-18: 10.10.0.14
      tinc-ubuntu-20: 10.10.0.15
    groups:
      - tinc_nodes
      - tinc_leaf_nodes

  - name: tinc-ubuntu-18
    image: ubuntu-18.04
    privileged: true
    command: /lib/systemd/systemd      
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro    
    etc_hosts:
      tinc-centos-7:  10.10.0.11
      tinc-centos-8:  10.10.0.12
      tinc-ubuntu-18: 10.10.0.14
      tinc-ubuntu-20: 10.10.0.15
    groups:
      - tinc_nodes
      - tinc_leaf_nodes

  - name: tinc-ubuntu-20
    image: ubuntu-20.04
    privileged: true
    command: /lib/systemd/systemd 
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro    
    etc_hosts:
      tinc-centos-7:  10.10.0.11
      tinc-centos-8:  10.10.0.12
      tinc-ubuntu-18: 10.10.0.14
      tinc-ubuntu-20: 10.10.0.15
    groups:
      - tinc_nodes
      - tinc_leaf_nodes
