---
os: linux
dist: focal
language: python
python: 3.8
services:
  - docker
install:
  - python3 -m pip install molecule
  - python3 -m pip install molecule-docker
  - python3 -m pip install ansible
script:
  - molecule --version
  - molecule test # default scenario with ring topology
  - molecule test -s star
