---
# tasks file for tinc
- name: Install tinc
  package:
    update_cache: "{{ (ansible_os_family == 'debian') | ternary('yes', omit) }}"
    name: tinc
    state: "{{ tinc_package_state }}"
  tags:
    - tinc_install
    - install

- name: Ensure tinc netname directory exists
  file:
    path: "/etc/tinc/{{ tinc_netname }}/hosts"
    recurse: True
    state: directory

- name: Ensure tinc.conf contains connection to core nodes
  template:
    src: tinc.conf.j2
    dest: "/etc/tinc/{{ tinc_netname }}/tinc.conf"
    mode: "0644"
  notify:
    - Restart Service
  tags: connection

- name: Create tinc-up file
  template:
    src: tinc-up.j2
    dest: "/etc/tinc/{{ tinc_netname }}/tinc-up"
    mode: 0755
  notify:
    - Restart Service

- name: Create tinc-down file
  template:
    src: tinc-down.j2
    dest: "/etc/tinc/{{ tinc_netname }}/tinc-down"
    mode: 0755
  notify:
    - Restart Service

- name: Ensure tinc hosts file binds to physical ip address
  lineinfile:
    dest: "/etc/tinc/{{ tinc_netname }}/hosts/{{ inventory_hostname | replace('.','_') | replace('-','_') }}"
    regexp: "^Address ="
    line: "Address = {{ tinc_control_plane_bind_ip }}"
    create: yes
    mode: "0644"
  when: inventory_hostname in groups['tinc_spine_nodes']
  notify:
    - Restart Service

- name: Ensure subnet ip address is properly set in tinc host file
  lineinfile:
    dest: "/etc/tinc/{{ tinc_netname }}/hosts/{{ inventory_hostname | replace('.','_') | replace('-','_') }}"
    regexp: "^Subnet ="
    line: "Subnet = {{ tinc_vpn_ip }}/32"
    mode: "0644"
    create: yes
  when: tinc_mode == 'router'
  notify:
    - Restart Service

- name: Check whether /etc/tinc/netname/hosts/inventory_hostname contains public key
  lineinfile:
    dest: "/etc/tinc/{{ tinc_netname }}/hosts/{{ inventory_hostname | replace('.','_') | replace('-','_') }}"
    line: "-----END RSA PUBLIC KEY-----"
  check_mode: yes
  register: contains_publickey_ending

# this is necessary because the public key will not be generated (non-interactively) if the private key already exists
- name: Delete private key and regenerate keypair if public key is absent from tinc hosts file
  file:
    path: "/etc/tinc/{{ tinc_netname }}/rsa_key.priv"
    state: absent
  when: contains_publickey_ending.changed
  tags:
    #Ansible lint recommends this to be handler, but this would make the role more complex.
    - skip_ansible_lint

- name: Create tinc private key (and append public key to tincd hosts file)
  command: "tincd -n {{ tinc_netname }} -K{{ tinc_key_size }}"
  args:
    creates: "/etc/tinc/{{ tinc_netname }}/rsa_key.priv"
  notify:
    - Restart Service

- name: Get tinc hosts file after key creation
  slurp:
    src: "/etc/tinc/{{ tinc_netname }}/hosts/{{ inventory_hostname | replace('.','_') | replace('-','_') }}"
  register: tinc_host_file

- name: Upload all hosts files on each host
  copy:
    dest: "/etc/tinc/{{ tinc_netname }}/hosts/{{ item | replace('.','_') | replace('-','_') }}"
    content: "{{ hostvars[item]['tinc_host_file']['content'] | b64decode }}"
    mode: 0755
  loop: "{{ ansible_play_batch }}"
  when: item != inventory_hostname
  notify:
    - Restart Service

- name: Add nodes to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].tinc_vpn_ip }}"
    line: "{{ hostvars[item].tinc_vpn_ip }} {{ item }}"
    state: present
  when: hostvars[item].tinc_vpn_ip is defined
  with_items: "{{ ansible_play_batch }}"
  tags:
    - tinc_internal_hosts
    - molecule-notest # https://github.com/ansible-community/molecule/issues/959

- name: Enable tinc with UCI
  template:
    src: openwrt-tinc-uci-config.j2
    dest: /etc/config/tinc
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "OpenWrt"
  tags:
    - uci
  notify:
    - Restart Service
  
- name: Ensure tinc is enabled
  service:
    name: "{{ tinc_service_name }}@{{ tinc_netname }}"
    daemon_reload: yes
    enabled: yes
  when:  ansible_os_family != "OpenWrt"