---
- name: restart service
  service:
    name: "{{ tinc_service_name }}"
    state: restarted
    enabled: yes
  when: ansible_service_mgr != "systemd"

- name: restart service with systemd
  systemd:
   daemon_reload: yes
   name: "{{ tinc_service_name }}"
   state: restarted
   enabled: yes
  when: ansible_service_mgr == "systemd"
