---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    packages:
      debian:
        - rsync
        - inetutils-ping
        - iproute2
      redhat:
        - iproute
  tasks:

  - name: Install base packages
    package:
      update_cache: "{{ ((ansible_os_family|lower) == 'debian') | ternary('yes', omit) }}"
      name: "{{ packages[(ansible_os_family|lower)] }}"
      state: present

  - name: Re-collect network facts required after installation iproute
    setup:
      gather_subset: network

  - name: Include ansible-tinc
    include_role:
      name: ansible-tinc
