---
- name: Converge
  hosts: all
  gather_facts: yes
  tasks:

  - name: Apt update and install rsync, ping, iproute
    apt:
      update_cache: yes
      name:
        - rsync
        - inetutils-ping
        - iproute2
      state: present
    when: ansible_os_family == "Debian"

  - name: Yum install iproute to fix undefined ansible_default_ipv4.address
    yum:
      name: iproute
      state: present
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"

  - name: Re-collect network facts required after installation iproute
    setup:
      gather_subset: network

  - name: Include ansible-tinc
    include_role:
      name: ansible-tinc
