---
- name: Verify
  hosts: all
  gather_facts: no
  tasks:

  - name: Ping all nodes over VPN
    command: "ping -c 1 {{ item }}"
    with_items: "{{ ansible_play_batch }}"
    changed_when: false
    register: ping_results

  - name: Show ping results
    debug:
      var: ping_results