---
- name: Verify
  hosts: all
  gather_facts: no
  tasks:

  - name: Ping all nodes over VPN
    command: "ping -c 1 {{ item }}"
    with_items: "{{ ansible_play_batch }}"
    changed_when: false
    register: _ping

  - name: Show ping info
    debug:
      var: _ping

  - name: Show vpn hosts data
    command: "cat /etc/tinc/{{ tinc_netname }}/hosts/*"
    changed_when: false
    register: _hosts

  - name: Debug hostfiles
    debug:
      var: _hosts

